version: '3'
services:
  medbuddy-sv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - medbuddy-db
  medbuddy-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: medbuddy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

